### ISSUE TITLE
Me again, i know.

### ISSUE THREAD

**Issue by ben-17benson** [lanmaster53/recon-ng#106]
Yep, its me again. Where in the wiki would i find the new syntax? Trying to set a location this tine after setting source ip using ipinfodb
Thanks in advance!

**Comment by ben-17benson** [comment]
I think ive got it now, dw. Just having trouble with twitters api

**Comment by ben-17benson** [comment]
Different issue this time. Having an issue with the twitter api, saying its invalid even though i just created it with the twitter development page. Any ideas?

**Comment by lanmaster53** [comment]
I literally installed and used that module about 4 hours ago in class and it worked perfectly. Has to be something with your key or environment.

**Comment by ben-17benson** [comment]
I tried in both kali and termux, both of which returned the exact same error. Will look into making sure that the api key is correct. Never used twitters api before.

**Comment by ben-17benson** [comment]
Authenticity token error right? Trying to use it in terkux lol

**Comment by lanmaster53** [comment]
This isn't an actual issue, so this conversation is better had using the Slack workspace. You're more likely to find timely assistance there as well. Thanks!

https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#help
