### ISSUE TITLE
recon/domains-hosts/netcraft

### ISSUE THREAD

**Issue by dinhcongminh153** [lanmaster53/recon-ng#11]
i got issue that 
[!] 'Response' object has no attribute 'cookiejar'.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by lanmaster53** [comment]
This is a marketplace issue and has been properly reported at https://github.com/lanmaster53/recon-ng-marketplace/issues/30.
