### ISSUE TITLE
Shodan_ip disabled

### ISSUE THREAD

**Issue by jmmeacham** [lanmaster53/recon-ng#112]
What are the dependencies required to install shodan_ip? 
![2020-07-14_12-16-59](https://user-images.githubusercontent.com/33558155/87461729-0b314500-c5cc-11ea-9222-09cb750361f4.png)

Working with version 5.1.1

**Comment by jmmeacham** [comment]
![2020-07-15_11-41-58](https://user-images.githubusercontent.com/33558155/87577569-56ad2700-c690-11ea-8a6e-b7a28459881d.png)

**Comment by tsarboot** [comment]
idk if you manged to solve it but i think that if you install the module then add the key , the module stay disabled so :
1-download shodan outside of recon by typing `sudo pip3 install shodan `
2-remove the modules if you installed them already by `marketplace remove module_name` and reload 
3- add the api key and install the module

**Comment by lanmaster53** [comment]
the `marketplace info shodan_ip` tells you what dependencies must be independently installed prior to the modules loading successfully. @tsarboot's guidance is spot on.
