### ISSUE TITLE
Failed to establish new connection

### ISSUE THREAD

**Issue by mikias21** [lanmaster53/recon-ng#117]
I recently updated recon-ng after that when I try to install modules from the market place I'm having error: **HTTPSConnectionPool Failed to establish a new connection** and I can't install any modules . can anyone please help me.

**Comment by lanmaster53** [comment]
Is this still an issue? I am unable to replicate, so I am going to close this and assume that it was a network related issue.

**Comment by mikias21** [comment]
You are right it was a network issue it’s solved now thank you Very much
