### ISSUE TITLE
Error with the hibp_breach

### ISSUE THREAD

**Issue by BandidoPabs** [lanmaster53/recon-ng#12]
I'm getting the following error when trying to run the hibp_breach module.

I'm doing the following commands.

set source info@microsoft.com
run

[!] TypeError: 'NoneType' object is not iterable
File "/usr/share/recon-ng/modules/recon/contacts-credentials/hibp_breach.py", line 30, in module_run.

Could it be because I do not have any of the api keys installed?

**Comment by theraiserson** [comment]
I think the problem is, that the hibp-modules use the Haveibeenpwned-API v2.

https://haveibeenpwned.com/api/v2/

The API is outdated, and was replaced by v3. I did not have the time to go further, but on the first look i would say that we will need API-Keys for hibp in the future.

**Comment by lanmaster53** [comment]
This is a marketplace issue and has been properly reported at https://github.com/lanmaster53/recon-ng-marketplace/issues/47.
