### ISSUE TITLE
Google CAPTCHA triggered. No bypass available.

### ISSUE THREAD

**Issue by faizan-tallat** [lanmaster53/recon-ng#121]
Hi team i am facing that problem although i am not facing that in my firefox or in my chrome but still that showing that error will using recon-ng

**Comment by lanmaster53** [comment]
That's because Firefox and Chrome are browsers operated by a person. It's much more difficult to act like a human as a script, so Google detects and blocks. Right now, there is no way to handle this block with Recon-ng.

**Comment by Darkcast** [comment]
I know this a closed topic.
I tried to use the same query shown in the plugin on my browser (FF) to bypass the captcha but I dont get the captcha at all. I tried setting the verbosity to see if there something I am missing but I cant find how to set it.
is there anything I can try to fix it or do I have to wait it out ? and how long would that be ?

**Comment by c0d3x27** [comment]
im having this same problem i cant look up anything. why don't you guys add an option to add google search API to it?

**Comment by CERTiv** [comment]
I'm having this same problem. Any update on a possible solution?

Thank you

**Comment by Valeye11ow46** [comment]
Any solution?
