### ISSUE TITLE
modules load resolve each website :NDS ERROR

### ISSUE THREAD

**Issue by boapgt** [lanmaster53/recon-ng#124]
I'm a new fish.
I tried  reload ,uninstall,but no use.
and I also have use proxychains to opration set proxy ,but still no useful.
I don't know where the problem is.
here is the code:

```
[recon-ng][default] > modules search resolve
[*] Searching installed modules for 'resolve'...

  Recon
  -----
    recon/hosts-hosts/resolve
    recon/hosts-hosts/reverse_resolve
    recon/netblocks-hosts/reverse_resolve

[recon-ng][default] > modules load recon/hosts-hosts/resolve
[recon-ng][default][resolve] > options set SOURCE bbc.com
SOURCE => bbc.com
[recon-ng][default][resolve] > run
[*] bbc.com => DNS Error
```

**Comment by lanmaster53** [comment]
See below. It has to be an environmental thing. Something in your host system or on your network is disrupting DNS.

```
[recon-ng][default] > marketplace install recon/hosts-hosts/resolve
[*] Module installed: recon/hosts-hosts/resolve
[*] Reloading modules...
[recon-ng][default] > modules load recon/hosts-hosts/resolve
[recon-ng][default][resolve] > options set SOURCE bbc.com
SOURCE => bbc.com
[recon-ng][default][resolve] > run
[*] bbc.com => 151.101.0.81
[*] bbc.com => 151.101.64.81
[*] bbc.com => 151.101.128.81
[*] bbc.com => 151.101.192.81

-------
SUMMARY
-------
[*] 3 total (3 new) hosts found.
[recon-ng][default][resolve] > 
```

**Comment by boapgt** [comment]
As you say," host system or on your network is disrupting DNS"
Thks.I've already solve the problem.
The reason why i can't use DNS resolve is the net i'm using is campus LAN.
when i change to my mobile phone network to connect the laptop ,DNS resolve modules run successfully.


But I still don't knw why.
If you know ,can you tell me please?













At 2020-10-04 11:12:24, "lanmaster53" <notifications@github.com> wrote:

See below. It has to be an environmental thing. Something in your host system or on your network is disrupting DNS.

[recon-ng][default] > marketplace install recon/hosts-hosts/resolve
[*] Module installed: recon/hosts-hosts/resolve
[*] Reloading modules...
[recon-ng][default] > modules load recon/hosts-hosts/resolve
[recon-ng][default][resolve] > options set SOURCE bbc.com
SOURCE => bbc.com
[recon-ng][default][resolve] > run
[*] bbc.com => 151.101.0.81
[*] bbc.com => 151.101.64.81
[*] bbc.com => 151.101.128.81
[*] bbc.com => 151.101.192.81

-------
SUMMARY
-------
[*] 3 total (3 new) hosts found.
[recon-ng][default][resolve] >

**Comment by lanmaster53** [comment]
Apparently your campus is doing something to DNS that is affecting Recon-ng. There are a LOT of possibilities. There's no way for me to know without talking to the network engineer of your school, which is outside the scope of support that I provide for Recon-ng. You or your professor could take the problem to them though and they may be able to help you out.

**Comment by bonedaddy** [comment]
I'm getting this error from a kali linux VM. I dont think the issue is related to my network configuration, as running `ping <website>` returns the IP address just fine.

**Comment by lanmaster53** [comment]
Kali is not a typical OS and does a lot of stuff to the network stack of anonymity and stealth. I don't support Kali, so you'll have to address that with them directly.
