### ISSUE TITLE
Module installation failed

### ISSUE THREAD

**Issue by robertcerny** [lanmaster53/recon-ng#126]
Hi,
freshly installed 5.1.1 on both Kali Linux and Mac OS X.

[!] Module installation failed: dev/spyse_subdomains.
[!] Invalid response from module repository (404).

I tried to alter modules.yml but it seems to be regenerated every time. What's the correct way to disable/remove module?

Thanks

**Comment by lanmaster53** [comment]
Yep. There was an issue in the module index. I just pushed a fix. See https://github.com/lanmaster53/recon-ng-marketplace/commit/22c8a355c3aa9c51a7ab19ed7c9fc71215415db2. My apologies. Thanks for the heads up. Reopen if the issue persists.
