### ISSUE TITLE
Is it safe to use personal accounts API keys?

### ISSUE THREAD

**Issue by switchy7** [lanmaster53/recon-ng#129]
Hello is it  safe to use api keys of my personal accounts like Facebook and Twitter? i will not get blocked?

**Comment by switchy7** [comment]
no one can help with it?

**Comment by kpcyrd** [comment]
There's always going to be a risk to get your account suspended, you might get away with it, but nobody is going to guarantee you anything.

**Comment by switchy7** [comment]
thank  you
