### ISSUE TITLE
Unsupported operant types

### ISSUE THREAD

**Issue by Ali-Anomma** [lanmaster53/recon-ng#130]
When i run my hackertarget module (it is updated,so there is no outdate problem)

Unsupported operand type(s) for +=: 'int' and 'list'.
something is broken?

how to solve this problem?

**Comment by Ali-Anomma** [comment]
also,how to update recon-ng?
version check is disabled,i cant ensure to i have updated edition

**Comment by lanmaster53** [comment]
For module issues, please create issues on the marketplace repository at https://github.com/lanmaster53/recon-ng-marketplace. As far as version checking being disabled, you must be running Kali or something similar. I don't support the way they deploy Recon-ng, so you would have to consult with them directly. Thanks!
