### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by W-3B** [lanmaster53/recon-ng#131]
[!] HTTPConnectionPool(host='whois.arin.net', port=80): Read timed out. (read timeout=10).
[!] A request took too long to complete. If the issue persists, increase the global TIMEOUT option.
![Capture](https://user-images.githubusercontent.com/69099263/103296064-e7937700-4a12-11eb-848c-68adb762f15b.PNG)

**Comment by lanmaster53** [comment]
Is this a module error? If so, and it persists, please create an issue on the marketplace repo at https://github.com/lanmaster53/recon-ng-marketplace. Thanks!
