### ISSUE TITLE
There is no module named recon/domains-hosts/findsubdomains

### ISSUE THREAD

**Issue by c0d367** [lanmaster53/recon-ng#137]
In my recon-ng there is no module named recon/domains-hosts/findsubdomains

[](url)
![Screenshot at 2021-03-04 22-38-49](https://user-images.githubusercontent.com/64792340/110002457-5049e900-7d0d-11eb-8ba3-29bf9c217859.png)

screenshot from another youtube video
![Screenshot at 2021-03-04 22-42-55](https://user-images.githubusercontent.com/64792340/110003208-12999000-7d0e-11eb-963c-7d29f4b28635.png)

HOW CAN I SOLVE THIS ?

**Comment by lanmaster53** [comment]
Modules come and go from the marketplace for a lot of reasons. Youtube is a bad about presenting old data that can't be replicated with modern versions of the tool. This is likely a case where the module has been removed. You can check the marketplace repo at https://github.com/lanmaster53/recon-ng-marketplace to verify, as that's where all of the modules live. Thanks!
