### ISSUE TITLE
[!] 'NoneType' object is not subscriptable.

### ISSUE THREAD

**Issue by nihadtp** [lanmaster53/recon-ng#139]
[recon-ng][cusat][whoxy_whois] > db query select host from hosts

  +------------------------------+
  |             host             |
  +------------------------------+
  | xxx.ac.in                  |
  | xxxxxxx              |
  | www1.xxxxxx.xxx             |

[recon-ng][cusat][whoxy_whois] > options set SOURCE query SELECT host FROM hosts
SOURCE => query SELECT host FROM hosts
[recon-ng][cusat][whoxy_whois] > run

-----------
XXXXXXXX
-----------
[!] 'NoneType' object is not subscriptable.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by nihadtp** [comment]
> [recon-ng][cusat][whoxy_whois] > db query select host from hosts
> 
> +------------------------------+
> | host |
> +------------------------------+
> | xxx.ac.in |
> | xxxxxxx |
> | www1.xxxxxx.xxx |
> 
> [recon-ng][cusat][whoxy_whois] > options set SOURCE query SELECT host FROM hosts
> SOURCE => query SELECT host FROM hosts
> [recon-ng][cusat][whoxy_whois] > run
> 
> ## XXXXXXXX
> [!] 'NoneType' object is not subscriptable.
> [!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

My bad. didnt have api keys. please close

**Comment by lanmaster53** [comment]
Also, FTR, this is the core repository. The module repository is at https://github.com/lanmaster53/recon-ng-marketplace. Please file all module related issues there. Thanks!
