### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by pratiyushray** [lanmaster53/recon-ng#141]
After writing accurate commands and running it I am getting an error of permission denied.
Also, the HTML file is not exported on the desktop after successful command running.
![Error Permission Denied](https://user-images.githubusercontent.com/64453528/123990883-d3432d80-d9e7-11eb-8b7d-68c43fe75dbd.png)

**Comment by lanmaster53** [comment]
It looks like whichever user you are running Recon-ng with is not allowed to write to the Desktop. What does the `id` command say? And, does the root user even have a Desktop?
