### ISSUE TITLE
module/domain-hosts/mx_spf_ip adds a " in end of host/ip_address

### ISSUE THREAD

**Issue by hitem** [lanmaster53/recon-ng#154]
Hello guys!
Ive been looking around for the correct place to post this, apparently it was not over at Kali forum so im giving it a try here in hopes that we can get this resolved. I might have found a bug relating to mx_spf_ip module.
To be fair im not 100% sure this is the mx_spf_ip module itself, but when it populates the database it has added " in end of the line of ip_address & host field. So when i generate my lists some of them have a " which halts the next steps.
I have automated a string that removes any " when recon-ng has exited but i thought maybe this could be resolved somewhere else - im unable to find where the issue is (im very novice in python), so here i am.

here im running the module in Recon-ng:
![image](https://user-images.githubusercontent.com/8977898/156347746-75b3d3db-83fa-4946-9874-9fe9b4af70c2.png)

here i have output the result.html (html report), showing both host and ip_address field.
![image](https://user-images.githubusercontent.com/8977898/156347240-117606ef-6562-486f-85a2-5acd29dd7e36.png)
![image](https://user-images.githubusercontent.com/8977898/156347245-52d4134d-186c-4cd1-a16b-785ff0718bfc.png)

Anyone have the same issue or able to see whats going wrong?

my steps:
1. create workspace -> db insert (company, domains)
2. modules load recon/domains-hosts/brute_hosts -> run
3. modules load recon/domains-hosts/mx_spf_ip ->
(all other modules works fine and listing is great).

Greatly Appreciated.

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).
