### ISSUE TITLE
recon-ng netcraft module shows No results found.

### ISSUE THREAD

**Issue by garrywaraich** [lanmaster53/recon-ng#157]
I'm learning recon-ng and I'm trying to use Netcraft module on site bbc.com. But the terminal is not displaying result and producing "no result found" error.
However, the URL produced by this module is working in browser.

I'm working on this for the past day, and can't figure out why recon-ng cli is not displaying the result.

Any help is appreciated!

![recon-bbc](https://user-images.githubusercontent.com/102697041/160925491-6cde4e19-b786-4f0b-802f-8cbad02218ea.png)

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).
