### ISSUE TITLE
Having Issues with Shodan not working 

### ISSUE THREAD

**Issue by DDuffy92** [lanmaster53/recon-ng#160]
I have checked api key and source.  Not very clear on dependencies.  using the Marketplace info it looks as though the dependencies are installed. The 2 shodan modules I have not been able to get to work are   recon/domains-hosts/shodan_hostname and recon/hosts-ports/shodan_ip

**Comment by greentea47** [comment]
I'm also having this problem.  No errors are returned, even with DEBUG option set.  My API key is valid.

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).
