### ISSUE TITLE
Unable to load censys modules

### ISSUE THREAD

**Issue by dbclinton** [lanmaster53/recon-ng#168]
I'm running recon-ng v5.1.2 on Ubuntu 22.04. I installed all modules using

```
marketplace install all
```
...and things are running well in general. However, when I try to load any of the censys modules (with the exception of censysio, which does work), I get this error:

```
[recon-ng][demo] > modules load censys_email_address
[!] Invalid module name.
```
I've added my API key and also tried removing and then reinstalling the module. Nothing changes. 
Any ideas?
Thanks!

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).

A fix has been merged that may have addressed this issue.
