### ISSUE TITLE
ERRNO 2 NO SUCH FILE OR DIRECTORY 

### ISSUE THREAD

**Issue by GIG06** [lanmaster53/recon-ng#170]
Am new to ethical hacking and on a topic reconnaissance using recon-ng

![kaliREPORT](https://user-images.githubusercontent.com/116433435/197334363-75163e40-995e-4e5b-8e59-4030a1d105a8.png)

 had followed through all the instructions upto the point of creating a report then this error message pops up and i basically dont understand what to do to solve it ,kindly help.

**Comment by AE-001-1001** [comment]
had you not changed the "  FILENAME  " it would've worked by default...
