### ISSUE TITLE
Profiler Module Error

### ISSUE THREAD

**Issue by artemrobert** [lanmaster53/recon-ng#172]
Profiler module loads fine but throws an error on attempting to run. Running on MacOS Monterey 12.6.

"[!] Extra data: line 1 column 4 (char 3)."
"[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting."

**Comment by NeoCortex97** [comment]
I have the same problem un kubuntu 22.04.

**Comment by AlRodriguezGar14** [comment]
Same here. Kali Linux and MacOS Ventura

**Comment by Bullarandian** [comment]
same problem. did someone fix it?

**Comment by aldelgado0686** [comment]
can someone pls fix this ?!

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).

A fix has been merged to address this issue.
