### ISSUE TITLE
Version Check failed (ConnectionError)

### ISSUE THREAD

**Issue by sannidhya004** [lanmaster53/recon-ng#178]
I've tried changing the PROXY ,refreshing the marketplace but this problem still persist can anyone please provide a solution for this or recommend some other tool for the same 

![Screenshot_20221218_134316](https://user-images.githubusercontent.com/111215548/208288291-90d08e8f-5397-40de-a211-307eac8d6201.png)

**Comment by MrJcool** [comment]
I too am facing the same problem with my kali recon-ng v5.1.2

**Comment by lanmaster53** [comment]
All Recon-ng does is make simple web requests. If it is unable to reach the various resources it is trying to reach out to, then you will receive connection errors like this. Therefore, it has to be a local networking issue outside of Recon-ng.
