### ISSUE TITLE
[!] Unable to synchronize module index. (ConnectTimeout).

### ISSUE THREAD

**Issue by LOKESHG1234** [lanmaster53/recon-ng#179]
Hi,
I am using the updated recon-ng (v5.1.2) and installed it using the apt package manager while running the tool get started but at the top there is an error shown below in image. When I try to run 'marketplace search domain' I get an error showing me usage but I am unable to figure out.
All the steps I tried to solve it are shown in image below.
Kindly provide the assistance in solving this issue.
![Recon-ng_error](https://user-images.githubusercontent.com/63283533/210180182-7e715cf0-18e7-4a26-a0d0-a8c409618f19.png)

**Comment by farhat-glitch** [comment]
I am also getting same problm 
Plz solve it out

**Comment by mikey866** [comment]
Same problem please give a solution

**Comment by larok260** [comment]
Hi,

I resolved my problem by new installation. 
apt-get update
apt remove recon-ng
apt install recon-ng

**Comment by Shibzzz** [comment]
> Hi,
> 
> I resolved my problem by new installation. apt-get update apt remove recon-ng apt install recon-ng
> 
> Version after installation --> v5.0.1 is older but it works!


How did u installed older version of recon-ng?

**Comment by LOKESHG1234** [comment]
No I have not tried but if we install using apt it will install higher version. According to you I should mention lower version while installing. I even forget I raised this issue to be honest.

**Comment by Godwin-Abin** [comment]
#191 
I'm also having the same issue. Please fix this issue as soon as possible.

**Comment by Godwin-Abin** [comment]
> Hi,
> 
> I resolved my problem by new installation. apt-get update apt remove recon-ng apt install recon-ng
> 
> Version after installation --> v5.0.1 is older but it works!

How did you do that. Please share it. 🙏 🙏

**Comment by Abinbabubs** [comment]
same issue

**Comment by lanmaster53** [comment]
All Recon-ng does is make simple web requests. If it is unable to reach the various resources it is trying to reach out to, then you will receive connection errors like this. Therefore, it has to be a local networking issue outside of Recon-ng.
