### ISSUE TITLE
Update the Features Wiki page

### ISSUE THREAD

**Issue by WebBreacher** [lanmaster53/recon-ng#18]
Please update the Features page (https://github.com/lanmaster53/recon-ng/wiki/Features) with the latest correct documentation. There are older commands and options in there that do not accurately reflect how the tool is currently working. Some examples:

1. ```workspaces add``` --> ```workspaces create```
2. ```marketplace list``` --> ```marketplace search```

There are probably other issues in there that I did not mention above that could be adjusted to currently reflect the project too.

**Comment by lanmaster53** [comment]
Good catch. I think you found the last outliers. I reviewed the entire page and those were the only inaccuracies. Updated. Thanks Micah!
