### ISSUE TITLE
Cannot run ./recon-ng

### ISSUE THREAD

**Issue by Williamyau** [lanmaster53/recon-ng#181]
Tried initially to run ./recon-ng on kali, but replied back with a module not found error: No Module named 'idna'.
Then ran a sudo pip3 install python-requests which successfully install the requests.
But when I run the ./recon-ng it replied back with 'The 'requests' library you installed has been hijacked'. Is there a work around solution to this problem.

**Comment by lanmaster53** [comment]
Could be a lot of things, but most likely an environmental issue.

**Comment by lanmaster53** [comment]
I don't support the Kali distribution, so unless the issue also exists outside of that platform, any issues you have with Recon-ng on their platform would have to be resolved through them.
