### ISSUE TITLE
recon-ng error

### ISSUE THREAD

**Issue by otaku-tanjiro** [lanmaster53/recon-ng#185]
i am getting this error i don't know the reason and i am new linux user i am quite confused about why i am getting this error 
![Screenshot 2023-04-30 122930](https://user-images.githubusercontent.com/70824420/235340233-f103b0ac-509e-47bd-a855-bfb445269672.png)

**Comment by AE-001-1001** [comment]
one of 2 things I can think of.
You could have ports blocking it off from being downloaded.
Environment error, corrupt packages, etc.
as of May 16th, 11:45PM CST, it works on debian 11 for the most part.

**Comment by fathersayno** [comment]
same

**Comment by sk3744** [comment]
use AnonSurf or vpn and then search marketplace it will show the modules.
![recon-ng](https://github.com/lanmaster53/recon-ng/assets/73067211/ef4c3ec1-32d0-4285-8298-8bba91c48bb0)

**Comment by lanmaster53** [comment]
All Recon-ng does is make simple web requests. If it is unable to reach the various resources it is trying to reach out to, then you will receive connection errors like this. Therefore, it has to be a local networking issue outside of Recon-ng.
