### ISSUE TITLE
Errors while using hibp_breach

### ISSUE THREAD

**Issue by joeanderson** [lanmaster53/recon-ng#186]
I am receiving the following error message when using hibp_breach and hibp_paste modules. It processes the first user credential (name@domain.com) and then gives the error.
![error](https://github.com/lanmaster53/recon-ng/assets/11444844/4497c2c8-81fb-4b2c-8294-cbe368b52cf7)

Thanks in advance.

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).
