### ISSUE TITLE
Recon-ng marketplace error

### ISSUE THREAD

**Issue by Naichell** [lanmaster53/recon-ng#188]
![image](https://github.com/lanmaster53/recon-ng/assets/139937129/c8caf0eb-ecf3-4e84-ab0c-dac2aa47d7c4)

i am having problems when i use this command in recon-ng :”marketplace install all”

Returns:[!] Invalid Module Path.

can anyone help, its not a type error, ive entered this a hundred times and searched everywhere but cannot find an answer

**Comment by babug3178** [comment]
I have the same error, how can it be fixed?![image](https://github.com/lanmaster53/recon-ng/assets/83527118/4583f359-d2ff-480b-bf4e-45bd3893321e)

**Comment by sandy-0-0-7** [comment]
I have the same issue. Have you guys found a solution yet?

**Comment by Naichell** [comment]
> I have the same issue. Have you guys found a solution yet? 

I deleted my Kali Linux OS on my virtualbox and downloaded it again then did a graphical install.

Now it works.

**Comment by Naichell** [comment]
> I have the same error, how can it be fixed?![image](https://github.com/lanmaster53/recon-ng/assets/83527118/4583f359-d2ff-480b-bf4e-45bd3893321e)

I deleted my Kali Linux OS on my virtualbox and downloaded it again then did a graphical install.

Now it works.

**Comment by rawr-droid** [comment]
Type the Cat etc/nsswitch.conf and look for hosts line and the value should be files DNS, if there's anything that comes between the files DNS words, delete it with a text editor and save it.Hope this helps

**Comment by lanmaster53** [comment]
All Recon-ng does is make simple web requests. If it is unable to reach the various resources it is trying to reach out to, then you will receive connection errors like this. Therefore, it has to be a local networking issue outside of Recon-ng.
