### ISSUE TITLE
workspaces add <name>

### ISSUE THREAD

**Issue by Neurom8ncer** [lanmaster53/recon-ng#19]
The add feature seems broke? I can add within a module using SOURCE but cannot add as explained in the recon-ng wiki. create works fine. I am a noob, This site helped with ver 5

[https://geekwire.co.uk/recon-ng-v5-tutorial/](url)

[recon-ng][default] > workspaces add space 2
Manages workspaces

Usage: workspaces <create|delete|list|select> [...]

[recon-ng][default] > workspaces list

  +------------+
  | Workspaces |
  +------------+
  | space 1    |
  | default    |
  +------------+
)
[recon-ng][default] > workspaces add space 2
Manages workspaces

Usage: workspaces <create|delete|list|select> [...]

[recon-ng][default] > workspaces list

  +------------+
  | Workspaces |
  +------------+
  | space 1    |
  | default    |
  +------------+

[recon-ng][default] > workspaces create space 2

[recon-ng][space 2] > workspaces list

  +------------+
  | Workspaces |
  +------------+
  | space 1    |
  | space 2    |
  | default    |
  +------------+

is add gone?

thank you for your time

**Comment by lanmaster53** [comment]
I apologize. Just updated the wiki. The `workplace add` command was replaced with `workspace create`.

**Comment by wilsq36** [comment]
Maybe you should update the Wiki again, since you changed all the commands with new ones. The wiki is outdated with the older version, 4.9.x.

The older version was much easier to use. Additionally, how do we install the modules, that don't come with Recon-ng. You only show how to search for them.

**Comment by lanmaster53** [comment]
Yep, i've already made a note that the docs need some updates. I made some more changes to staging today that will further affect the wiki when I merge it into the master branch. As far as installing modules goes, you clearly are aware of the `marketplace search` command. If you look at the help for the `marketplace` command, or merely provide `marketplace` without any subcommand, you'll see that `install` is another subcommand alongside `search`. I'm certain I do that in the video posted on the Wiki and elude to it in the documentation. Is it more difficult to use? I don't think so. It's different, which means you need to learn the new commands, but the benefits provided by the marketplace far outweigh any detriments. In any case, thanks for your feedback.

**Comment by wilsq36** [comment]
God Evening,

Thanks for the thorough response. I actually went through your video and
saw exactly what you replied to me. Got most of the modules installed, just
have to figure out the keys and dependencies.

Awesome work.

Thank you.

**Comment by lanmaster53** [comment]
I believe it is in the help, but you can do a `marketplace install all` to install them all at once. But yes, you have to get the keys and deps worked out or you'll have a mess of errors to look at every time you load the modules. One of the advantages of the marketplace is only installing what you want and not having to deal with everything you don't. Enjoy!
