### ISSUE TITLE
unable to synchronize module index. (connectionerror) in (recon-ng)

### ISSUE THREAD

**Issue by deadlock007** [lanmaster53/recon-ng#191]
And also when I try to search marketplace for the domains
It shows 0 module found.
Please can anyone help me with this.

**Comment by Godwin-Abin** [comment]
I'm Also Getting The Issue like this. Please solve this issue. 
![image](https://github.com/lanmaster53/recon-ng/assets/94969757/17bed46e-d8b2-4ef3-8f20-890faff8b5bc)

**Comment by rawr-droid** [comment]
It's a network based error, when I tried service networking restart and some other network based commands it just gradually worked.idk if this helps but it's better to try it out

**Comment by rawr-droid** [comment]
Type the Cat etc/nsswitch.conf and look for hosts line and the value should be files DNS, if there's anything that comes between the files DNS words, delete it with a text editor and save it.Hope this helps

1
Reply

**Comment by sagarbindhani2003** [comment]
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files systemd
group:          files systemd
shadow:         files systemd
gshadow:        files systemd

**hosts:          files DNS 

> myhostname**didnot work

networks:       files

protocols:      db files
services:       db files
ethers:         db  files
rpc:            db files

netgroup:       nis

**Comment by Emmadiong** [comment]
Has anybody found a solution for this? I am currently facing this issue and it is frustrating.. please help
![20240214_025151](https://github.com/lanmaster53/recon-ng/assets/159973481/3b817aae-52ba-4463-a479-c15a620636e7)
![20240214_025124](https://github.com/lanmaster53/recon-ng/assets/159973481/c48a6f90-e2ac-4fdb-ad37-bc3fc2169e47)
