### ISSUE TITLE
Support py3.12

### ISSUE THREAD

**Issue by chenrui333** [lanmaster53/recon-ng#193]
While trying to migrate the release build to build against py3.12, I ran into some build failure as below:

<details>
<summary>error build log</summary>

```
  ==> /opt/homebrew/Cellar/recon-ng/5.1.2_1/bin/recon-ng -r /private/tmp/recon-ng-test-20231022-10034-1oxxlse/resource
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/recon-ng/5.1.2_1/bin/recon-ng", line 8, in <module>
      from recon.core import base
    File "/opt/homebrew/Cellar/recon-ng/5.1.2_1/libexec/recon/core/base.py", line 7, in <module>
      import imp
  ModuleNotFoundError: No module named 'imp'
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6601730464/job/17933077020
relates to Homebrew/homebrew-core#152053

**Comment by lanmaster53** [comment]
I don't support distribution via Homebrew, so unless the issue also exists outside of Homebrew, any issues you have with installing Recon-ng that way would have to be resolved through them.
