### ISSUE TITLE
Having an issue of  pgp_search

### ISSUE THREAD

**Issue by muler2009** [lanmaster53/recon-ng#194]
everything was set properly but while runnng it shows an error related to  HTTPConnectionPool(host='pgp.key-server.io', port=80): Max retries exceeded with url: ..
 can i get  a brief explanation the cause of the error and the respective solution.

**Comment by jamesmontanoh** [comment]
same

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).
