### ISSUE TITLE
hunter.io api key not recognized + trial search not working

### ISSUE THREAD

**Issue by aerisheaven** [lanmaster53/recon-ng#196]
![Screenshot (768)](https://github.com/lanmaster53/recon-ng/assets/123779096/87bd9967-c244-466e-be43-d0ea6e732121)
I've tried different domains as well removing and readding my api key. the source domain I set works on the hunter.io website itself, but i'd like to use recon-ng if possible

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).
