### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Eng-Mohamedkhaled** [lanmaster53/recon-ng#197]
Name: MailTester Email Validator
    Author: Tim Tomes (@lanmaster53)
   Version: 1.0

Description:
  Leverages MailTester.com to validate email addresses.

Options:
  Name    Current Value         Required  Description
  ------  -------------         --------  -----------
  REMOVE  True                  yes       remove invalid email addresses
  SOURCE  blueman123@yahoo.com  yes       source of input (see 'info' for details)

Source Options:
  default        SELECT DISTINCT email FROM contacts WHERE email IS NOT NULL
  <string>       string representing a single input
  <path>         path to a file containing a list of inputs
  query <sql>    database query returning one column of inputs

[recon-ng][default][mailtester] > options set SOURCE blueman123@yahoo.com
SOURCE => blueman123@yahoo.com
[recon-ng][default][mailtester] > run
[!] List index out of range.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
[recon-ng][default][mailtester] >

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).
