### ISSUE TITLE
ipinfodb how to limit rating

### ISSUE THREAD

**Issue by rogermanich** [lanmaster53/recon-ng#21]
Hi,
I am testing last version of recon-ng. I added a valid ipinfodb_api key and run this module. I receive an error about to limit the queries under two seconds per query. I cannot see any option to do this. the option LIMIT is true but it looks like it miss something. I don't know if it is actually a bug but I cannot see anything in the documentation.
thank you and great job.

**Comment by lanmaster53** [comment]
Hey Roger. This sounds like a module bug. Please file an issue using the proper template over in the marketplace repo at https://github.com/lanmaster53/recon-ng-marketplace after reading https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting. Thanks!
