### ISSUE TITLE
/bin/sh: 1: db: not found

### ISSUE THREAD

**Issue by CryptoCubik** [lanmaster53/recon-ng#25]
Working through The Hacker Playbook 3, and got to the section about discovery. Using a script ( https://github.com/leebaird/discover ) that makes use of a bunch of different discovery tools.

I've ironed out most of the kinks, but it seems to be having issue with recon-ng, and I'm not sure how to approach fixing this one. I get a lot of stuff like below:
```
[recon-ng][cyberspacekittens.com] > spool stop
[*] Spooling stopped. Output saved to '/tmp/networks'.
[recon-ng][cyberspacekittens.com] > 
[recon-ng][cyberspacekittens.com] > spool start /tmp/subdomains
[*] Spooling output to '/tmp/subdomains'.
[recon-ng][cyberspacekittens.com] > db query SELECT DISTINCT host,ip_address FROM hosts ORDER BY host ASC
[*] Command: db query SELECT DISTINCT host,ip_address FROM hosts ORDER BY host ASC
/bin/sh: 1: db: not found
[recon-ng][cyberspacekittens.com] > db query SELECT DISTINCT host,ip_address FROM ports ORDER BY host ASC
[*] Command: db query SELECT DISTINCT host,ip_address FROM ports ORDER BY host ASC
/bin/sh: 1: db: not found
[recon-ng][cyberspacekittens.com] > spool stop
[*] Spooling stopped. Output saved to '/tmp/subdomains'.
[recon-ng][cyberspacekittens.com] > 
[recon-ng][cyberspacekittens.com] > spool start /tmp/usernames
[*] Spooling output to '/tmp/usernames'.
[recon-ng][cyberspacekittens.com] > db query SELECT username FROM profiles ORDER BY username ASC
[*] Command: db query SELECT username FROM profiles ORDER BY username ASC
/bin/sh: 1: db: not found
[recon-ng][cyberspacekittens.com] > spool stop
[*] Spooling stopped. Output saved to '/tmp/usernames'.
[recon-ng][cyberspacekittens.com] > 
[recon-ng][cyberspacekittens.com] > exit
cat: networks-tmp: No such file or directory
```

**Comment by kpcyrd** [comment]
`db` is not a valid recon-ng subcommand and it's trying to run it as an external program instead, which also fails because there's no db binary in the `$PATH` (causing this slightly cryptic error).

**Comment by CryptoCubik** [comment]
Great, thank you, that was very helpful. Is trying to run the db command normal recon-ng behavior? In which case what software / packages should I install to fix it?

**Comment by lanmaster53** [comment]
`db` actually IS a valid command. It's part of the changes in v5 of the framework where I consolidated all database related commands as subcommands under `db`. The problem you may be having is running the modern version of Lee's discovery scripts against an older version of Recon-ng.

**Comment by lanmaster53** [comment]
This isn't a Recon-ng issue, so I am going to close it. If you have further issues, you could hit up Lee about his scripts, or ask in the Recon-ng slack for general guidance regarding anything specific to Recon-ng.
