### ISSUE TITLE
Please add a notes column to the ports table in the database

### ISSUE THREAD

**Issue by 0xd0ug** [lanmaster53/recon-ng#27]
Would it be possible to please add a "notes" column to the "ports" table as freeform text, so modules can put notes about the port. This could include service information as imported from Nmap, for example.

**Comment by 0xd0ug** [comment]
I put in a pull request to address this feature request. I know database changes are a big deal, so I totally understand if this can't go in until down the road or never. But thanks for your consideration!

**Comment by lanmaster53** [comment]
I saw your response on the PR, but I want to continue the conversation here as this is the more appropriate place.

I don't want to add something just to add it. If there is a universal use case other than supporting one person's notes, then I am all for it. FWIW, I have had more than one person ask for a column in the ports table to store banner information. So this likely makes sense and immediately makes several modules more powerful, as they provide this information but it isn't currently stored.

To go a little deeper here, I've thought about a dynamic data store such as NoSQL but concluded that the type of data Recon-ng harvests is best stored in a structured database. However, I've been entertaining the idea of creating a hybrid field (or just another normal field) in each table where people can store whatever the heck they want. But there would be strict use cases for this. Such as no module will be allowed to use it as a default source of input or output. One idea I had for this was adding a notes column to each table, then providing an interface command for quickly adding a note to a record without having to build a SQL query yourself. What are your thoughts on this? This feels like a feature people will want.

**Comment by 0xd0ug** [comment]
I like your idea for a banner column in ports. I think it would fit in with nmap -sV output. Yeah, I'm all for a structured database too. I noticed the profiles table has a notes column, but I'm not sure what it's used for. TBH I had planned on using a notes column in ports for a module I've written (and hope to submit soon), but it turns out I can just record the data I collect in the host column anyway, so no biggie.

Your idea for notes is good. I would use it just to mark "done" or "To Do" on ports as I went through them checking them out.  Or for putting notes by contacts you "reached out" to during a social engineering attack. Hope I'm not butting in--recon-ng is really useful, so I definitely want to give back; let me know if you want me to code this up. Cheers!

**Comment by 0xd0ug** [comment]
Thanks! Code updated. I did the pull request against master -- I figured you want me to move it to staging but then I realized you're doing all that API work there, so I just left it against master. Please let me know if I need to re-do the table changes when you're done. I'm pretty new to forking and pulling--I've just been a long-time cloner.

**Comment by 0xd0ug** [comment]
Closed old pull request against master and opened a new one against staging. I'm sure there was a more efficient way to do this, but I'm a GitHub n00b, so there we are. :-)

**Comment by lanmaster53** [comment]
I'm pretty sure you did it the only way you can. At least that's what everyone else does. Thanks!
