### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by e2002e** [lanmaster53/recon-ng#3]
Hey, I don't understand much about this update, right now I'm unable to launch any module with the "use" function, also it feels weird there is now some kind of marketplace.
recon-ng was one of the best framework imo so where is it ?

**Comment by lanmaster53** [comment]
It was made very clear upon release that there were major changes and updated documentation to help navigate them. https://github.com/lanmaster53/recon-ng/wiki ... Which includes https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting. Closing...
