### ISSUE TITLE
Interesting files 

### ISSUE THREAD

**Issue by hexadiam** [lanmaster53/recon-ng#36]
Running interesting files yields results yet also throws an error:

recon-ng][acme] > modules load interesting_files
[recon-ng][acme][interesting_files] > run
[*] http://www.acme.org:80/robots.txt => 200. 'robots.txt' found!
[*] http://www.acme.org:80/sitemap.xml => 200. 'sitemap.xml' found!
[!] Can't concat str to bytes.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
[recon-ng][acme][interesting_files] >

**Comment by lanmaster53** [comment]
This is the wrong repository. Please click the link in the error message you pasted above and follow the guidance there. Thanks!
