### ISSUE TITLE
recon-ng", line 16

### ISSUE THREAD

**Issue by meetgyn** [lanmaster53/recon-ng#41]
root@xxxx:/opt/ferramentas/osint/recon-ng# python3 recon-ng
  File "recon-ng", line 16
    print(f"{Colors.R}[!] Module 'readline' not available. Tab complete disabled.{Colors.N}")
                                                                                           ^
Help  men

**Comment by lanmaster53** [comment]
That error doesn't even make any sense because I am capturing that exception and accounting for it. I believe it has something to do with the f-string formatting. You are probably running an older version of Python 3, before those were supported. What version are you running?

**Comment by meetgyn** [comment]
i have python 3.7.4

**Comment by lanmaster53** [comment]
Well, that became available in Python 3.6, so 3.7.4 should be fine. There is definitely something different about your environment. What you pasted above is not the entire error because it is missing the traceback and exception type. Please send the entire error so we have additional context.

**Comment by greyjedimaster** [comment]
Here is the error message in full:

File "./recon-ng", line 16
    print(f"{Colors.R}[!] Module 'readline' not available. Tab complete disabled.{Colors.N}")
                                                                                           ^
SyntaxError: invalid syntax

I am using python3.6 and installed with pip3.

**Comment by lanmaster53** [comment]
I need more information. OS you are using, method of install, command used to launch, etc. The only time I can replicate this error is when I launch Recon-ng with Python 2, or something under Python 3.6. It's an environmental issue. Based on that error, the only 2 things it can be is your version of python not supporting the `print` function or f-strings.

**Comment by greyjedimaster** [comment]
I was using Ubuntu 16.04. Turns out, updating to 18.04 resolved the issue.

**Comment by lanmaster53** [comment]
Yep. Had to be an environmental thing. Likely the same for the OP too.

**Comment by lanmaster53** [comment]
https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#prerequisites
