### ISSUE TITLE
pushpins module google maps display is shaded in grey

### ISSUE THREAD

**Issue by jsolderitsch** [lanmaster53/recon-ng#42]
I am using recon-ng 4.9.0 from inside ADHD 3.1.

The pushpins twitter module works. The reporting module works but when the map view opens in Firefox, the map is shaded with a grey color. I get an alert saying "Do you own this site" too.

I have entered my Google Maps API key.

I remember some time ago that the map in the reporting module did not have this behavior.

Is there anything I can do?
<img width="890" alt="Screen Shot 2019-11-02 at 3 09 49 PM" src="https://user-images.githubusercontent.com/23091236/68075778-dc977500-fd82-11e9-89ba-ab7989da008d.png">

**Comment by lanmaster53** [comment]
Upgrade to a version that isn't very, very old. :-D ADHD looks to be way out of date. This issue has been fixed in recent versions. Please file an issue with the maintainers of the ADHD distro.

**Comment by jsolderitsch** [comment]
What is the oldest python 3 version for which recon-ng will work?

ADHD version of python 3 is 3.5 and trying to update to 3.6 shows some key expiration errors from the apt-get update command.

I know this is not a recon-ng problem but I would like to update recon-ng within ADHD.

I will raise an issue with ADHD as well.

**Comment by lanmaster53** [comment]
3.6+ https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#prerequisites
