### ISSUE TITLE
Worth mentioning to use pip3 on install

### ISSUE THREAD

**Issue by digininja** [lanmaster53/recon-ng#44]
For systems which still have Python2 as the default, running

`pip install -r REQUIREMENTS`

Will install the Python2 versions, it might be worth stressing to run `pip3` instead.

**Comment by lanmaster53** [comment]
I hesitate to give environmentally dependent guidance. With Python 3 being the only maintained branch going forward, Recon-ng already being Python 3, and the wiki clearly identifying Python 3 as a prerequisite, I will let the use of pip3 be assumed and expect folks to know how to use their environment to run the framework. I realize this is a "must be this tall to ride" approach to the issue, and some folks won't like it, but it's more maintainable than trying to give guidance for any and all environmental configurations.
