### ISSUE TITLE
Case-sensitivity in "options"

### ISSUE THREAD

**Issue by BBhacKing** [lanmaster53/recon-ng#49]
It would be helpful if the word "OPTIONS" (both global and per-module) did not have to be entered as all-caps. It already tab-completes INTO all caps if you start it in lower-case and hit the tab key...

If allowing these as lower-case is unacceptable, maybe the response from the framework could be made more helpful. Right now it gives the same "Invalid option name" error whether I type garbage or a valid option name that's just not all-caps. Maybe it could mention that these are case-sensitive,  for example, and/or give a list of valid names.

Example:
```
[recon-ng][example][hackertarget] > options set source example.com
[!] Invalid option name.
[recon-ng][example][hackertarget] > options set SOURCE example.com
SOURCE => example.com
```

**Comment by lanmaster53** [comment]
This is a good point. I remember there being a reason I did this, so I'll have to look back at my notes, but it was years ago and I was probably a bad design decision that could have been fixed another way.

**Comment by BBhacKing** [comment]
Background:
I only reported this because the behavior has changed in 5.x.

They've always been _listed_ with upper-case names. But in 4.x they could be _set_ in any case. In 5.x, if you get the case wrong, the framework has no idea what you mean and offers no guidance.

Here's 4.9.5:

```
[recon-ng][default] > set threads 5
THREADS => 5
[recon-ng][default] > set THREADS 12
THREADS => 12
[recon-ng][default] > set threAds 13
THREADS => 13
```
And here's 5.1.0:
```
[recon-ng][example] > options set threads 9
[!] Invalid option name.
[recon-ng][example] > options set THREADS 11
THREADS => 11
```

**Comment by lanmaster53** [comment]
Interesting. That's something I explicitly changed. Must be something specific to Python 3.
