### ISSUE TITLE
bing_domain_web module error

### ISSUE THREAD

**Issue by kybernetx** [lanmaster53/recon-ng#5]
When **run** command is sent to **bing_domain_web** module the following error is returned

`[!] Name 'urllib' is not defined.`
`[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.`

**Comment by cam-barts** [comment]
Hey @kybernetx.  urllib is a standard library module, and was split into a couple different parts in python3. Are you using python 3, and what operating system are you on? I am running python 3.7 on linux and I am unable to replicate that error.

**Comment by lanmaster53** [comment]
@kybernetx did we end up resolving this through our convo in Slack?

**Comment by kybernetx** [comment]
Somebody in slack at the time was able to replicate it but I've used it since and it seems to work fine.

**Comment by lanmaster53** [comment]
If I recall, you were having an environment issue with your local python environment. Anyway, glad it's working for you now. Thanks for closing.

**Comment by l4jos** [comment]
I get 'statuscode' when 'run'.

[recon-ng][default][bing_linkedin_contacts] > run
[*] Searching Bing API for: bla.do
[!] 'statusCode'.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

Could because api not valid? (I found one invalid probably, I dont own a stupid creditcard to aquire a api)

**Comment by lanmaster53** [comment]
@l4jos That's a different module, and I'm pretty sure there's an issue for that one too.

**Comment by l4jos** [comment]
There is no 'statuscode' defined in the bing_linkedin_contacts module anyway.

**Comment by lanmaster53** [comment]
Also, this is the issue tracker for the framework, not the modules. Please see the marketplace repository for module issues. Thanks! https://github.com/lanmaster53/recon-ng-marketplace/issues

**Comment by lanmaster53** [comment]
OH!!! I see what you're saying. There's a mixin in the core that is being used by these modules that is breaking on `statusCode`. Yeah, that's a potential issue. Reopening. I need to see if I can replicate. This has been working, so either Bing changed something, or there is an error condition that I'm not accounting for. Thank you for reporting!

**Comment by l4jos** [comment]
Youre welcome! I used the module before without an API. I never had any Bing API but module worked before. Why?

**Comment by l4jos** [comment]
Statuscode could return in stdout if remote URI changes as far as I k'now. I suppose Bing changed something, because I can't sind any statuscode as well in core files so far.

**Comment by l4jos** [comment]
Youre welcome! statusCode could return in stdout if remote URI for requests changes (eg 404 not found), as far as I k'now. I suppose Bing changed this and not core-related, I can't sind any statusCode in core files so far, as well.

**Comment by l4jos** [comment]
Usually 'statusCode' means there is no response (0, unreachable or means the response body is empty, which mostly the reason should be specific).

**Comment by l4jos** [comment]
Actually I got a 401 unauthorized.

#elif 'error' in resp.json():
elif resp.status_code == 401:
raise framework.FrameworkException(f"{resp.json()['statusCode']}: {resp.json()['message']}")

Probably has to do with no Bing API key. I was able in the past to use the Linkedin module without API, I don't know why.

**Comment by lanmaster53** [comment]
So there are/have been several different bing-based modules that interacted with LinkedIn. One of them, likely the one you've used in the past, scraped web results. This one uses the API. So, your issue will likely be fixed by adding the Bing API key, but I should still be handling that condition better. Did the framework not warn you that you didn't have the key set when you installed/loaded the module?

**Comment by cam-barts** [comment]
bing_linkedin_contacts definitely requires a key, and unless the mixin or framework is supposed to handle that gracefully, there's not any logic that checks for a key. Is that something that should be in the module? I can add that if it's necessary

**Comment by l4jos** [comment]
Yes I spent some time to find out about the error I got. It was all about the missing API, lol. Still don't know why it worked without API someday, as far as I can remember.
