### ISSUE TITLE
Version check failed (FileNotFoundError).

### ISSUE THREAD

**Issue by iocohen** [lanmaster53/recon-ng#50]
[!] Version check failed (FileNotFoundError).
[*] Your version of Recon-ng does not match the latest release.
[*] Please consider updating before further use.
[*] Remote version:  5.1.0
[*] Local version:   0

I've upgraded recon-ng and i have this FilenotFound error.

**Comment by lanmaster53** [comment]
I need more context. Platform, means of install, how you upgraded, did it work before, etc. Based on the info you provided so, the VERSION file doesn't exist in your application's directory. That's not a condition the framework expects because that would be an incomplete install.

**Comment by lanmaster53** [comment]
Closed due to inactivity and inability to replicate.

**Comment by jonzatlmi** [comment]
Also having this issue, installed via git clone, and pip, windows 10 recon-ng 5.1.1

**Comment by lanmaster53** [comment]
I ran through the steps just to do it and it works. Building a Docker image does this as well and also works. It has to be an access permissions error. Are you installing in root space then trying to run it with a user that doesn't have read access? Other than mucking with the files after clone, this is the only thing that can cause this error within the the 2 lines of code that make u the affected block. https://docs.python.org/3/library/exceptions.html#FileNotFoundError
