### ISSUE TITLE
cannot add a domain

### ISSUE THREAD

**Issue by azamet90** [lanmaster53/recon-ng#53]
[!] Unsupported operand type(s) for +=  'int' and 'list'. recon-ng
this error is what i do get and this command is what i give

 db insert domains facebook.com or google.com or whatever

edit:

now i see that i have the old version of recon-ng it was preinstalled on kali linux...
how to update it?

**Comment by lanmaster53** [comment]
Kali is responsible for maintaining the version they push out in their repos. You could try installing manually using the guidance in the wiki. See https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#installation. I recommend the Docker approach.

**Comment by azamet90** [comment]
> Kali is responsible for maintaining the version they push out in their repos. You could try installing manually using the guidance in the wiki. See https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#installation. I recommend the Docker approach.

on me same thing happened on the source file that for i turn back to kali repo because i dont know how to install this tool to system that i can run it direct anywhere from terminal
