### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by azamet90** [lanmaster53/recon-ng#54]
im using latest version of kali first of all i did not understand this:
https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#v4-to-v5

i already have it on my repos do i need to do this section:

> Upgrading
> v4 to v5
> 
> If you're reading this, then you've likely been sent here by Recon-ng v4 in search of guidance for upgrading to the latest version. Upgrading can only be done for source installs of Recon-ng. Recon-ng installs through Linux distributions with their own repositories (i.e Kali) must be handled by the distribution.
> 
> Since Recon-ng v5 is hosted in a new repository on a different provider, the normal source upgrade procedure of git pull won't work. The repository must be migrated to the new source. There are several ways to do this:
> 
>     Remove the old version completely and replace it with the new version. From the Recon-ng install directory:
> 
>     cd ..
>     rm -rf recon-ng
>     git clone https://github.com/lanmaster53/recon-ng.git
>     cd recon-ng
> 
>     Update the remote URL of the current repository. From the Recon-ng install directory:
> 
>     git remote set-url origin https://github.com/lanmaster53/recon-ng.git
>     git reset --hard HEAD~1
>     git pull
> 
> IMPORTANT! Recon-ng has changed dramatically! Once Recon-ng has been migrated, new dependencies must be installed. See the Installation section below for more information.
> 
> From this point, upgrading a source installation is as simple as navigating to the Recon-ng install directory and issuing the git pull command.
> Migrating Keys
> 
> Keys used by the framework are stored in an independent SQLite3 database at "~/.recon-ng/keys.db". When installing a new instance of Recon-ng on the same machine, no migration is necessary. The new Recon-ng instance will recognize and use the existing key database. However, in order to access the key database on another system, the key database must me manually moved to the same location on the new machine, where it can be recognized and used by any instance of Recon-ng running there.

my another question is the command list is not explained anywhere i want to see the source options but show options is not working how to know the commands?

**the tool looks good but sorry for saying that: the viki and man page and help command results are very poor designed**

edit:
okay i found it finally but now i get this error:

```
[recon-ng][default][netcraft] > show credentials
[*] No data returned.
[recon-ng][default][netcraft] > options
Manages the current context options

Usage: options <list|set|unset> [...]

[recon-ng][default][netcraft] > options list

  Name    Current Value  Required  Description
  ------  -------------  --------  -----------
  SOURCE  default        yes       source of input (see 'show info' for details)

[recon-ng][default][netcraft] > options set SOURCE kali.org
SOURCE => kali.org
[recon-ng][default][netcraft] > options list

  Name    Current Value  Required  Description
  ------  -------------  --------  -----------
  SOURCE  kali.org       yes       source of input (see 'show info' for details)

[recon-ng][default][netcraft] > show info
Shows various framework items

Usage: show <companies|contacts|credentials|domains|hosts|leaks|locations|netblocks|ports|profiles|pushpins|repositories|vulnerabilities>

[recon-ng][default][netcraft] > show domains
[*] No data returned.
[recon-ng][default][netcraft] > run
[!] 'Response' object has no attribute 'cookiejar'.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

```

**Comment by lanmaster53** [comment]
Kali is always behind. In fact, I don't even know if they are maintaining it in their repos anymore. You'll have to take that up with them. The sections in the wiki are clearly marked as "Installing on Kali Linux" and "Installing from Source", so I don't know how much more clear I can be.

The error you posted at the end is a module issue, not a framework issue. This is the framework repo. Also, there's this: https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting. There is already an open issue on this topic.
