### ISSUE TITLE
idea - `do_status()` calls

### ISSUE THREAD

**Issue by jnazarioCensys** [lanmaster53/recon-ng#57]
i propose this feature specifically to support external APIs with budgeted quotas - a `status` command. 

i modified my local copy of recon-ng (/usr/share/recon-ng/recon/core/module.py) to stub out a `do_status()` command and then call it like this in a module:

```
    def do_status(self, *unused):
        api_key = self.get_key('whoxy_key')
        url = 'http://api.whoxy.com/?key={0}&account=balance'.format(api_key)
        resp = self.request('GET', url).json()
        self.output(resp)
```

this then prints out my account balance. 

```
[recon-ng][datacom][whoxy_company] > status
[*] {'status': 1, 'live_whois_balance': 500, 'whois_history_balance': 750, 'reverse_whois_balance': 229}
```

a number of APIs support this query (for free in most cases), and it helps budget my pivots.

**Comment by lanmaster53** [comment]
I'm ok with a module that does this, but I don't want to rely on a 3rd party resource to provide any core functionality, which this does. Cool idea though. Please create and submit a module to the marketplace. Thanks!
