### ISSUE TITLE
Solved - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by gagaltotal** [lanmaster53/recon-ng#59]
File "./recon-ng", line 16
    print(f"{Colors.R}[!] Module 'readline' not available. Tab complete disabled.{Colors.N}")
                                                                                           ^
SyntaxError: invalid syntax

I use Ubuntu LTS 16.04
and python version 3.5 does it have to upgrade to version 3.6?

and after I read the issue https://github.com/lanmaster53/recon-ng/issues/41
I found the problem solving comments should upgrade to Ubuntu 18.04 LTS?

**Comment by gagaltotal** [comment]
My Solved this Upgrade with Python 3.6.9
and upgrade your operating system ubuntu 18.04 LTS
use Python 3.6.9 install package use pip done..

**Comment by lanmaster53** [comment]
https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#installation
