### ISSUE TITLE
shell and cd not working

### ISSUE THREAD

**Issue by leebaird** [lanmaster53/recon-ng#6]
<img width="463" alt="shell" src="https://user-images.githubusercontent.com/4013039/61914758-388e6a00-af07-11e9-8522-3c493ffa32c3.png">

**Comment by lanmaster53** [comment]
It's not a fully interactive shell. It just shells out individual commands. `cd` has never and will never work in this context. Also, I didn't write the shell command into the framework. It comes embedded in the cmd module.
