### ISSUE TITLE
Python >= 3.6.0 setup issue with pip requirements (jsonschema needs to be prior to 3.0.0)

### ISSUE THREAD

**Issue by jabberwock** [lanmaster53/recon-ng#61]
I am using python 3.8.1 via pyenv, and I get the following when attempting to pip install -r REQUIREMENTS"

`pip install -r REQUIREMENTS`
[truncated]
ERROR: flasgger 0.9.3 has requirement jsonschema<3.0.0, but you'll have jsonschema 3.2.0 which is incompatible.

This can be easily addressed by issuing the following command:
`pip install 'jsonschema==2.6.0'`

**Comment by lanmaster53** [comment]
I believe we discussed in Slack. 3.8 not yet supported until dependency support catches up.

**Comment by lanmaster53** [comment]
Looking at Flassger's code, their requirements show this: https://github.com/flasgger/flasgger/blob/master/requirements.txt. This shouldn't be an issue anymore.

**Comment by lanmaster53** [comment]
I'm confused... I looked up Flasgger on PyPi (https://pypi.org/project/flasgger/) and the homepage points to a different repo than I linked above, which I thought was official. The one above has 0.9.2 as latest release, but PyPi has 0.9.3, which corroborates with what pip is telling you. The nicobatty repo must be the official repo even though it says its a fork. The 0.9.3 release has this https://github.com/nicobatty/flasgger/blob/release-0.9.3/requirements.txt which does not jive with what pip is telling you. So something is goofed. Perhaps you have cached an older version locally or something?

**Comment by lanmaster53** [comment]
From my Docker environment...

```
/recon-ng # pip install flasgger
Requirement already satisfied: flasgger in /usr/local/lib/python3.7/site-packages (0.9.3)
Requirement already satisfied: Flask>=0.10 in /usr/local/lib/python3.7/site-packages (from flasgger) (1.1.1)
Requirement already satisfied: jsonschema>=2.5.1 in /usr/local/lib/python3.7/site-packages (from flasgger) (2.6.0)
Requirement already satisfied: mistune in /usr/local/lib/python3.7/site-packages (from flasgger) (0.8.4)
Requirement already satisfied: PyYAML>=3.0 in /usr/local/lib/python3.7/site-packages (from flasgger) (5.2)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/site-packages (from flasgger) (1.13.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.7/site-packages (from Flask>=0.10->flasgger) (2.10.3)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.7/site-packages (from Flask>=0.10->flasgger) (0.16.0)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.7/site-packages (from Flask>=0.10->flasgger) (1.1.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.7/site-packages (from Flask>=0.10->flasgger) (7.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask>=0.10->flasgger) (1.1.1)
/recon-ng # 
```

`jsonschema>=2.5.1`, which jives with what the repo says. I have no idea why your system says flasgger 0.9.3 requires jsonschema<3.0.0, when clearly it does not.

**Comment by jabberwock** [comment]
My first guess is that it must be a PyEnv issue. I will attempt with Docker. Thanks for testing this!

**Comment by lanmaster53** [comment]
I enjoy a good code mystery. Let me know what you discover.

**Comment by lanmaster53** [comment]
Closed due to inactivity.
