### ISSUE TITLE
TypeError: '>='

### ISSUE THREAD

**Issue by zimah11** [lanmaster53/recon-ng#64]
Traceback (most recent call last):
  File "./recon-ng", line 57, in <module>
    recon_ui(args)
  File "./recon-ng", line 42, in recon_ui
    x.start(*options)
  File "/usr/share/recon-ng/recon/core/base.py", line 73, in start
    self._init_workspace(workspace)
  File "/usr/share/recon-ng/recon/core/base.py", line 200, in _init_workspace
    self._load_modules()
  File "/usr/share/recon-ng/recon/core/base.py", line 438, in _load_modules
    self._update_module_index()
  File "/usr/share/recon-ng/recon/core/base.py", line 348, in _update_module_index
    self.debug('Updating index file...')
  File "/usr/share/recon-ng/recon/core/framework.py", line 288, in debug
    if self._global_options['verbosity'] >= 2:
TypeError: '>=' not supported between instances of 'str' and 'int'

Hi please an idea

**Comment by lanmaster53** [comment]
It looks like you set your verbosity to an invalid value. Verbosity should be an integer between 0-2. Check the `base` configuration item in your `~/.recon-ng/workspaces/{workspace}/config.dat` file and see if you have the `VERBOSITY` option stored with a setting other than an integer. Removing that config setting all together should reset it to the default on the next load and fix your issue.

**Comment by zimah11** [comment]
thank you very much for your answer, my problem is solved, and thank you for your wonderful work that you do swore loved having your super level Provenance : Courrier pour Windows 10 De : lanmaster53Envoyé le :lundi 13 janvier 2020 17:14À : lanmaster53/recon-ngCc : zimah11; AuthorObjet :Re: [lanmaster53/recon-ng] TypeError: '>=' (#64) It looks like you set your verbosity to an invalid value. Verbosity should be an integer between 0-2. Check the base configuration item in your ~/.recon-ng/workspaces/{workspace}/config.dat file and see if you have the VERBOSITY option stored with a setting other than an integer. Removing that config setting all together should reset it to the default on the next load and fix your issue.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lanmaster53** [comment]
My pleasure.
