### ISSUE TITLE
error:Not enough values to unpack 

### ISSUE THREAD

**Issue by sishomit** [lanmaster53/recon-ng#65]
i removed and installed recon-ng but its still showing the same message the message while i the moudle after setting the target source
[!] Not enough values to unpack (expected 2, got 1).

**Comment by lanmaster53** [comment]
There is not nearly enough information here to help you. Also, if you are setting a target source, then you must be getting this error from a module. This is the core repository. Module issues should be filed in the marketplace repo. See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting for more information. Thanks.
