### ISSUE TITLE
recon-ng Windows support

### ISSUE THREAD

**Issue by jonzatlmi** [lanmaster53/recon-ng#67]
issues with the __version__ variable
issues with the modules

other than that, seems ot run perfect on Python376 on Windows 10

Please PLEASE consider making a go at normal functionality for us Windows users.  I tried, I failed.  If you can't do long term support, at least get current master working so it can be forked off and someone can maintain that fork separately.

**Comment by lanmaster53** [comment]
"issues with the version variable
issues with the modules

other than that, seems ot run perfect on Python376 on Windows 10"

So other than everything, it seems to work perfect on Windows 10. :-P I assure you that you will run into other issues using it on Windows. Unfortunately, there are just some things in the Python language that aren't cross-platform. I suggest running it in Docker on Windows. That should do what you need. My official stance is that I have no intention on making it run in Windows natively.
