### ISSUE TITLE
Not working: recon-ng in Kali (Windows Subsystem for Linux (WSL))

### ISSUE THREAD

**Issue by HeeresS** [lanmaster53/recon-ng#7]
I have recon-ng installed in  Kali running as a windows subsystem.
When I start by typing `./recon-ng` it starts but says: `[*] No modules enabled/installed.` (see screenshot).

Is this because running Kali as a subsystem for Linux is causing problems, or something else?

_Screenshot:_
![Screenshot from recon-ng](https://user-images.githubusercontent.com/48584256/62041753-52c09480-b1f4-11e9-96a8-1ee631329f2a.png)

**Comment by AgeOfMarcus** [comment]
I'm having the same issue here. I tried using `apt-get` to install as well but no difference.

**Comment by AgeOfMarcus** [comment]
@HeereS installing from `https://LaNMaSteR53@bitbucket.org/LaNMaSteR53/recon-ng.git` provides a temporary fix as it is a slightly older version

**Comment by lanmaster53** [comment]
This is not an issue. There are a lot of changes and you are experiencing the biggest of them. See the wiki. https://github.com/lanmaster53/recon-ng/wiki

**Comment by kpcyrd** [comment]
I'd suggest showing a hint about what to do next if no modules are detected, like it's done in sn0int:

![quickstart](https://user-images.githubusercontent.com/7763184/62070544-fd5ba600-b23a-11e9-905c-0548612f84b5.jpg)

**Comment by lanmaster53** [comment]
I appreciate the suggestion.

FWIW, the note says, "No modules enabled/installed." If that doesn't make you think, "hm... perhaps I should install a module." then I'm not really sure what to say. The next logical step to installing a module would be, "What happens if I type the word 'help'?" That's a simple thought plus 5 keystrokes (if you count the enter key) and you have your answer. Plus a plethora of information in the wiki which is only a few clicks away.

This is a really silly thing to be spending time on. Must be this tall to ride... :-D

**Comment by lanmaster53** [comment]
I apologize for coming off so harsh, but please read the feedback and think about things before you file an issue. I spend way too much time responding to these kinds of issues that aren't even really issues. I prefer to spend that time improving the tool. I and others put a lot of time into updating documentation and creating videos, etc. Please respect our time and effort by at least skimming over these things for your answer before posting an issue. Thanks.

**Comment by rationalthinker1** [comment]
type in `marketplace install all`

**Comment by robert2669** [comment]
@rationalthinker1 i tried marketplace install all, did no good. Please suggest

**Comment by robert2669** [comment]
How would i add domains ? i get below error

[recon-ng][default] > add domains twitter.com
[!] Invalid command: add domains twitter.com.
[recon-ng][default] > domains add twitter.com
[!] Invalid command: domains add twitter.com.
[recon-ng][default] >

**Comment by lanmaster53** [comment]
Hey @robert2669, have you looked at the wiki yet? 90% of the questions asked can be answered by looking through the wiki and watching the videos there. Give it a shot.

**Comment by default015** [comment]
For those of you who are confused and don't know how to install the modules with the latest version of recon-ng 

marketplace refresh
marketplace install all

**Comment by robert2669** [comment]
I did as suggested and I get the below error.

[cid:image001.png@01D579BE.ABA4A960]

I am running Kali in VM, Installed VM Ware pro in Win 10.

Regards,
Ramesh Guru.

**Comment by lanmaster53** [comment]
> I did as suggested and I get the below error. [cid:image001.png@01D579BE.ABA4A960] I am running Kali in VM, Installed VM Ware pro in Win 10. Regards, Ramesh Guru. From: default015 <notifications@github.com> Sent: Tuesday, October 1, 2019 11:28 AM To: lanmaster53/recon-ng <recon-ng@noreply.github.com> Cc: robert2669 <robert2669@hotmail.com>; Mention <mention@noreply.github.com> Subject: Re: [lanmaster53/recon-ng] Not working: recon-ng in Kali (Windows Subsystem for Linux (WSL)) (#7) For those of you who are confused and don't know how to install the modules with the latest version of recon-ng marketplace refresh marketplace install all — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flanmaster53%2Frecon-ng%2Fissues%2F7%3Femail_source%3Dnotifications%26email_token%3DANJU6LTKD5AJYHPX6JYTEB3QMLRGHA5CNFSM4IHRAXJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAACASY%23issuecomment-536879179&data=02%7C01%7C%7Cbd255a1a13c54930c42508d746344e33%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637055062767467559&sdata=rtt2adt19dXNvy0tldStmRuJ61EnEhdpKdCQ9BNZv0U%3D&reserved=0>, or mute the thread<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANJU6LQ4DRE75GIQZ2N33DLQMLRGHANCNFSM4IHRAXJQ&data=02%7C01%7C%7Cbd255a1a13c54930c42508d746344e33%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637055062767477567&sdata=Z3mVpd8DsxfIlPMx6TUI793wuJ%2FNOAMJwA%2Bm%2Fj2hrPc%3D&reserved=0>.

I don't see an error in your response. Please provide more detail. Also, keep in mind that Kali is rarely up to date and does some funky things to add tools to their repositories. I recommend doing a clean install according to the documentation on the wiki.

**Comment by RushiLj** [comment]
> type in `marketplace install all`

Thanks men.. i was having the same issue.. and you just solved it thanks a lot love you brother..

**Comment by b3nam** [comment]
Hi guys.i want add API into recon-ng . please help me.

**Comment by lanmaster53** [comment]
> Hi guys.i want add API into recon-ng . please help me.

This is a feature request for a new thread, but no need to create it. I'm already working on a REST API and will be releasing it shortly.

**Comment by sdkohan** [comment]
> For those of you who are confused and don't know how to install the modules with the latest version of recon-ng
> 
> marketplace refresh
> marketplace install all

thank you buddy....nice and easy

**Comment by Victor-Kariuki** [comment]
> How would i add domains ? i get below error
> 
> [recon-ng][default] > add domains twitter.com
> [!] Invalid command: add domains twitter.com.
> [recon-ng][default] > domains add twitter.com
> [!] Invalid command: domains add twitter.com.
> [recon-ng][default] >

try running
`db insert domains domainname`

**Comment by lanmaster53** [comment]
> > How would i add domains ? i get below error
> > [recon-ng][default] > add domains twitter.com
> > [!] Invalid command: add domains twitter.com.
> > [recon-ng][default] > domains add twitter.com
> > [!] Invalid command: domains add twitter.com.
> > [recon-ng][default] >
> 
> try running
> `db insert domains domainname`

All of this stuff and more is in the Wiki. Rather than answer questions directly, I recommend folks point people to the wiki or it creates threads like this that act as support channels rather than real issues. Please do not ask or answer any more direct usage questions here. Please see the wiki. If you don't find what you're looking for there, you will find directions for accessing the Recon-ng Slack channel, where you can ask for support that isn't covered in the wiki. Thanks!
