### ISSUE TITLE
[Module] whois_miner requires a secure connection

### ISSUE THREAD

**Issue by T145** [lanmaster53/recon-ng#71]
The URL generated by the module works, but iff `http` is changed to `https`. Otherwise, an `HTTPSConnectionPool(host='whois.arin.net', port=443)` error is thrown, which is caused by an `SSLError`.

ReconNG usage has been done on the latest Kali release after running:
```bash
sudo apt-get update -y && sudo apt-get upgrade --with-new-pkgs -y && sudo apt-get autoremove -y
```

**Comment by lanmaster53** [comment]
What version of Recon-ng is Kali using? Kali is usually way behind and I haven't seen anything from them about updating their repos since I released v5 a very long time ago. As of this message we are at v5.1.1.

**Comment by T145** [comment]
Ah that could be the issue then, b/c I'm on `5.0.1`. That may be something to update in the documentation, so other weird errors can be avoided.

**Comment by lanmaster53** [comment]
Cool. Try again with 5.1.1 and let me know how it works out. If it persists, open an issue in the marketplace repo. This is the framework repo. Thanks!
