### ISSUE TITLE
KALI Python3 Default - Unable to Synchronize Version Check (Invalid URL)

### ISSUE THREAD

**Issue by theLaxerz** [lanmaster53/recon-ng#72]
I am using a VPN OF COURSE.. it actually looks to me a parsing issue when I do a marketplace search prior to moving to 3 from 2, I was getting nothing now I get the response from hacker target but the error from HackerTarget is:

Module installation Failed: rec....
Failed to Parse: https://raw.githubusercontent.com/lanmaster53/recon-ng-modules/master/modules/recon/domains-hosts/hackertarget.py

**Comment by theLaxerz** [comment]
Usage: index <module|all> <index>

[recon-ng][default] > marketplace install all
[!] Supporting file download for discovery/info_disclosure/cache_snoop failed: (av_domains.lst).
[!] Module installation aborted.
[!] Failed to parse  https //raw.githubusercontent.com/lanmaster53/recon-ng-modules/master/data/av_domains.lst.
[recon-ng][default] >

**Comment by lanmaster53** [comment]
I'm not sure what you're saying. Are you saying that you are trying to use Python 2? Also, what version of Recon-ng is Kali using? They are notoriously behind.

**Comment by theLaxerz** [comment]
Unfortunately I know they are, I was saying I tried by 2 and 3

**Comment by lanmaster53** [comment]
i did some investigating. That only happens when the framework can't reach the Github repo, which is a hard coded URL. This is working for everyone else, so something in your environment is keeping you from hitting Github.

**Comment by theLaxerz** [comment]
I figured as it only has happened to VERY few people I will take a relook

**Comment by s0i37** [comment]
I had the same.
The root cause:
```
from urllib3.util import parse_url
parse_url('https://api.github.com/')
...
module 'six' has no attribute 'ensure_str'
....
LocationParseError: Failed to parse: https://api.github.com/
```
It happens because of your `urllib3` and `six` dont corrensponds to each other.
It is because you probably have two distribution of `urllib3` from `apt-get` and from `pip3`.
For me the soluition was updating `urllib3` and `six` to the latest versions via `pip3` and disabling these libs from `apt-get`

**Comment by ChiefJinchuriki** [comment]
I found out what this was! I was having the same issue using parrot. I was using anon surf with it. I ended up having to change my identity so if you're getting this it's because the tor node or vpn node is blocking you from connecting so change identity or select new vpn connection and it'll work.

**Comment by hopemarc-ai** [comment]
Please guys I'm a newbie in cyber, here is my own challenge "Unable to synchronize module index."  (ConnectionError). Someone please help
