### ISSUE TITLE
[Feature] Add a "contributors" field to module metadata

### ISSUE THREAD

**Issue by T145** [lanmaster53/recon-ng#74]
Presently there's only the "author" field, which only allows for one contributor, being the module's initial creator. It would nice if there were another field to at least mention other contributors, and foster more of a developer movement around this program.

**Comment by lanmaster53** [comment]
We are already doing this. For example, the interesting_files module has this:

```
'author': 'Tim Tomes (@lanmaster53), thrapt (thrapt@gmail.com), Jay Turla (@shipcod3), and Mark Jeffery',
```
