### ISSUE TITLE
ipinfodb error

### ISSUE THREAD

**Issue by eliassal** [lanmaster53/recon-ng#76]
On a fresh new kali linux 2020, I run ipinfodb it returns back 1 result for the domain in the SOURCE option not for all domains in the hosts table also it works correcly when I hand a file with several domains but it never updates the hosts table with the locations

Thanks for your help

**Comment by lanmaster53** [comment]
Please see your other issue. Same response here. Potential old version of Recon-ng and wrong issue tracker. Closing. Please reopen in the right place if needed. Thanks!
