### ISSUE TITLE
recon-ng executable error

### ISSUE THREAD

**Issue by donBuba** [lanmaster53/recon-ng#8]
Hi, i was testing the application and give me a error like this:
  File "./recon-ng", line 16
    print(f"{Colors.R}[!] Module 'readline' not available. Tab complete disabled.{Colors.N}")
                                                                                           ^
SyntaxError: invalid syntax
The version of python is 3.4.3

**Comment by kpcyrd** [comment]
your python version is probably too old, which operating system do you use?

**Comment by lanmaster53** [comment]
Yep. Recon-ng requires Python 3.6+ (as mentioned on https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#prerequisites) because it uses f-strings, which weren't added until Python 3.6.
