### ISSUE TITLE
Can't send a command

### ISSUE THREAD

**Issue by mikaxy** [lanmaster53/recon-ng#87]
The command **SET** is invalid on modules
for example i can't send the command set creator on html module, recon-ng return me invalid command.

Thanks for help

recon-ng 5.1.1 on kali linux 2020

**Comment by lanmaster53** [comment]
`options set ...`

The command structure has changed a bit. See the Recon-ng wiki. There are videos and documentation about the changes.

**Comment by AswinBarath** [comment]
Went through the same problem and
options set ...
And the above command worked
@lanmaster53 thanks for sharing it.

Google ranked this issue page above the Recon-ng wiki, hence got to know about it here.
