### ISSUE TITLE
what's the 'f'

### ISSUE THREAD

**Issue by yodatron** [lanmaster53/recon-ng#9]
I was trying to install recon-ng on my computer. I installed the old repo from bitbucket and it went through the start up on terminal, found out it was out of date. 'rm-rf recon-ng'. Then went through the install from "Getting Started" page and got errors. I went through the base.py file, the core.py and the framework.py file and removed all the 'f' from about 100lines and it finally loaded again. I will try it out to see if there are anymore things giving me trouble. If this was the wrong way to handle these errors please let me know and help me fix it.

**Comment by cam-barts** [comment]
Hi @yodatron, it sounds like you are removing the f-strings. They are new to python 3.6, and require 3.6 or later to work.

**Comment by yodatron** [comment]
ah....ok...uh...would this affect the modules? When I moved to the new repo and reinstalled I ran 'ls -a' in recon-ng dir and the data and modules files that were in the bitbucket repo did not show up in the github clone so the problem there was prior to the f-string removal, so I doubt it.

**Comment by cam-barts** [comment]
No, this would not affect the modules. The modules have been separated into their own repository, located [here](https://github.com/lanmaster53/recon-ng-marketplace). Its best to just clone that into .recon-ng.

**Comment by yodatron** [comment]
ok...thanks a lot...it's been a while since I have had to do this...trying to rebuild somethings that I lost on another distro until I can get that issue fixed...so a lot of this is like having to learn over again....

**Comment by lanmaster53** [comment]
> No, this would not affect the modules. The modules have been separated into their own repository, located [here](https://github.com/lanmaster53/recon-ng-marketplace). Its best to just clone that into .recon-ng.

This is actually the wrong approach. The marketplace for installing modules is built into recon-ng. Check out the `marketplace` command for installing modules. The framework comes with none installed.  The wiki has all of this information there along with a video that talks about the differences.

**Comment by yodatron** [comment]
Hey, just got all the emails on this issue....Thanks, I will try this again.
